name: RME-ACS Binary build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    binary_build_acpi_all:
        name: ACPI target for RME issue
        runs-on: ubuntu-latest

        steps:
            - name: Checkout rme-acs repository
              uses: actions/checkout@v4
              with:
                  path: 'rme'

            - name: Performing the pre-build steps
              uses: "./rme/.github/actions/pre-build"

            - name: Set up EDK2 environment and build Rme.efi
              run: |
                  cd edk2
                  export GCC49_AARCH64_PREFIX=/opt/cross/arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
                  export PACKAGES_PATH=$PWD/edk2-libc
                  source edksetup.sh
                  make -C BaseTools/Source/C
                  sed -i 's/SBSA/RME/g' MdePkg/Include/IndustryStandard/Acpi61.h
                  sed -i 's/#define PLATFORM_BASEFVP 1/#define PLATFORM_BASEFVP 0/g' ShellPkg/Application/rme-acs/val/include/platform_overrride_fvp.h
                  source ShellPkg/Application/rme-acs/tools/scripts/acsbuild.sh

            - name: Save Rme.efi as an artifact
              uses: actions/upload-artifact@v4
              with:
                name: Rme_acpi_all.efi
                path: edk2/Build/Shell/DEBUG_GCC49/AARCH64/Rme.efi
                if-no-files-found: error

    binary_build_acpi_da:
        name: ACPI target for DA issue
        runs-on: ubuntu-latest

        steps:
            - name: Checkout rme-acs repository
              uses: actions/checkout@v4
              with:
                  path: 'rme'

            - name: Performing the pre-build steps
              uses: "./rme/.github/actions/pre-build"

            - name: Set up EDK2 environment and build Rme.efi
              run: |
                  cd edk2
                  export GCC49_AARCH64_PREFIX=/opt/cross/arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
                  export PACKAGES_PATH=$PWD/edk2-libc
                  source edksetup.sh
                  make -C BaseTools/Source/C
                  sed -i 's/SBSA/RME/g' MdePkg/Include/IndustryStandard/Acpi61.h
                  source ShellPkg/Application/rme-acs/tools/scripts/acsbuild.sh

            - name: Save Rme.efi as an artifact
              uses: actions/upload-artifact@v4
              with:
                name: Rme_acpi_da.efi
                path: edk2/Build/Shell/DEBUG_GCC49/AARCH64/Rme.efi
                if-no-files-found: error
