name: RME-ACS Binary build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    binary_build_acpi_all:
        name: RME-ACS Binary build on ACPI target for all suites
        runs-on: ubuntu-latest

        steps:
            - name: Performing the pre-build steps
              uses: ./.github/workflows/pre-build-workflow.yml
